### ISSUE TITLE
Write a bootloader

### ISSUE THREAD

**Issue by connorkuehl** [squidboylan/rsv6#2]
Well, we need one of these.

- [ ] Choose an asm flavor (nasm, Intel, AT&T)
- [ ] In real mode, zero out segmentation registers
- [ ] Enable the A20 line
- [ ] Create and load Global Descriptor Table (GDT)
- [ ] Long jump to trick the CPU into noticing that we loaded the GDT, now we're in 32-bit protected mode
- [ ] Set stack pointer
- [ ] Load the kernel off of the disk and into memory
- [ ] Using the ELF header of the kernel binary, find the entry point address
- [ ] Enter the kernel

**Comment by squidboylan** [comment]
I'm looking into this, using https://wiki.osdev.org/Rolling_Your_Own_Bootloader as a source as well as other online sources

**Comment by squidboylan** [comment]
closed by #4
