### ISSUE TITLE
Generate a bootblock

### ISSUE THREAD

**Issue by connorkuehl** [squidboylan/rsv6#3]
A virtual hard disk. This should be done as part of the build (but not every time unless it's cleaned away because we will eventually have a file system and want changes to persist between boots).

The virtual hard disk is made in xv6 using `dd` to write a chunk of zeroes to a file. This is our virtual hard disk.

The bootloader must live within the boot sector (the first 512 bytes of the virtual disk).

The kernel image should be written after the bootloader (byte 513 and beyond).

**Comment by squidboylan** [comment]
closed by #4
